### ISSUE TITLE
Could not install on non AES computer

### ISSUE THREAD

**Issue by mpenagar** [MoneroOcean/node-cryptonight-hashing#12]
- Debian GNU/Linux 9 (stretch)
- g++ 6.3.0
- CPU: Intel(R) Atom(TM) CPU D525   @ 1.80GHz (flags: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf eagerfpu pni dtes64 monitor ds_cpl tm2 ssse3 cx16 xtpr pdcm movbe lahf_lm dtherm)

```
$ npm install https://github.com/MoneroOcean/node-cryptonight-hashing.git#v3.0.3

> cryptonight-hashing@3.0.3 install /home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: se entra en el directorio '/home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/build'
  CC(target) Release/obj.target/cryptonight-hashing/xmrig/crypto/asm/cnv2_main_loop.o
  CXX(target) Release/obj.target/cryptonight-hashing/multihashing.o
../multihashing.cc:23:2: warning: #warning Using software AES [-Wcpp]
 #warning Using software AES
  ^~~~~~~
../multihashing.cc: In member function ‘virtual void CCryptonightAsync::HandleOKCallback()’:
../multihashing.cc:206:37: error: ‘async_resource’ was not declared in this scope
             callback->Call(2, argv, async_resource);
                                     ^~~~~~~~~~~~~~
../multihashing.cc: In member function ‘virtual void CCryptonightLightAsync::HandleOKCallback()’:
../multihashing.cc:271:37: error: ‘async_resource’ was not declared in this scope
             callback->Call(2, argv, async_resource);
                                     ^~~~~~~~~~~~~~
../multihashing.cc: In member function ‘virtual void CCryptonightHeavyAsync::HandleOKCallback()’:
../multihashing.cc:338:37: error: ‘async_resource’ was not declared in this scope
             callback->Call(2, argv, async_resource);
                                     ^~~~~~~~~~~~~~
cryptonight-hashing.target.mk:116: fallo en las instrucciones para el objetivo 'Release/obj.target/cryptonight-hashing/multihashing.o'
make: *** [Release/obj.target/cryptonight-hashing/multihashing.o] Error 1
make: se sale del directorio '/home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/nodeproxy/.nvm/versions/node/v6.9.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.9.0-4-amd64
gyp ERR! command "/home/nodeproxy/.nvm/versions/node/v6.9.2/bin/node" "/home/nodeproxy/.nvm/versions/node/v6.9.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing
gyp ERR! node -v v6.9.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Linux 4.9.0-4-amd64
npm ERR! argv "/home/nodeproxy/.nvm/versions/node/v6.9.2/bin/node" "/home/nodeproxy/.nvm/versions/node/v6.9.2/bin/npm" "install" "https://github.com/MoneroOcean/node-cryptonight-hashing.git#v3.0.3"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! cryptonight-hashing@3.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cryptonight-hashing@3.0.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cryptonight-hashing package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cryptonight-hashing
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cryptonight-hashing
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/nodeproxy/xmr-node-proxy/npm-debug.log
```

I got the error while updating xmr-node-proxy.

**Comment by MoneroOcean** [comment]
This is not related to AES. Please move to node v8:

```
nvm install v8.11.3
nvm alias default v8.11.3
```

**Comment by MoneroOcean** [comment]
And remove node_modules directory in xmr-node-proxy before repeating update.

**Comment by mpenagar** [comment]
Updated to  node v8, removed node_modules directory, updated xmr-node-proxy and worked.

Thanks!
