### ISSUE TITLE
node-gyp related installation issue on Windows

### ISSUE THREAD

**Issue by Tmayne** [MoneroOcean/node-cryptonight-hashing#27]
Attempting to install on Windows 10 with `npm install cryptonight-hashing` fails with the following output.

`C:\xxxxxxxxx\node_modules\cryptonight-hashing>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\no de-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\no de-gyp.js" rebuild )                                                                                    The system cannot find the path specified.                                                              
gyp: Call to 'uname -a \| grep "aarch64" >/dev/null && echo "-march=armv8-a+crypto -flax-vector-conversi ons -DXMRIG_ARM=1" \|\| (uname -a \| grep "armv7" >/dev/null && echo "-mfpu=neon -flax-vector-conversions  -DXMRIG_ARM=1" \|\| echo "-march=native")' returned exit status 255 while in binding.gyp. while trying to  load binding.gyp                                                                                       gyp ERR! configure error                                                                                
gyp ERR! stack Error: `gyp` failed with exit code: 1                                                    
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node -gyp\lib\configure.js:345:16)                                                                           gyp ERR! stack     at ChildProcess.emit (events.js:189:13)                                              
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)            
gyp ERR! System Windows_NT 10.0.17763                                                                   
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\n ode_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"                                                      gyp ERR! cwd D:\windowscoin\node_modules\cryptonight-hashing                                            gyp ERR! node -v v10.15.3                                                                               
gyp ERR! node-gyp -v v3.8.0                                                                             
gyp ERR! not ok                                                                                                                                               npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})                                                                                                                                                      npm ERR! code ELIFECYCLE                                                                                
npm ERR! errno 1                                                                                        
npm ERR! cryptonight-hashing@8.0.1 install: `node-gyp rebuild`                                          npm ERR! Exit status 1                                                                                  
npm ERR!                                                                                                
npm ERR! Failed at the cryptonight-hashing@8.0.1 install script.                                        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
---`
I have checked that node-gyp is indeed sane, and built bcrypt and several other libraries to test this. I have already tried the fixes in this thread: https://github.com/nodejs/node-gyp/issues/1195 It seems to be an issue with the code.

**Comment by MoneroOcean** [comment]
Windows is not really supported at this moment.

**Comment by cryptojunkie36** [comment]
What would more or less be the requirements to add support? Any idea what would need to be changed?

**Comment by duyk16** [comment]
> Windows is not really supported at this moment.

I just install on Linux. Can I install it on MacOS?

**Comment by thundo** [comment]
Any plans to reevaluate expanding support to Windows?

It would be greatly appreciated,
Thanks
